# Generated by Django 3.2.15 on 2022-09-05 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataEvent', models.DateField()),
                ('desc', models.CharField(max_length=200)),
                ('merc', models.CharField(max_length=100)),
                ('typeMerc', models.CharField(max_length=50)),
                ('odds', models.CharField(max_length=50)),
                ('invest', models.FloatField()),
                ('retor', models.FloatField()),
                ('pl1', models.IntegerField()),
                ('pl2', models.IntegerField()),
                ('statusTrader', models.CharField(max_length=10)),
            ],
        ),
    ]
